### ISSUE TITLE
有计划支持API->媒体->地图里的接口吗?

### ISSUE THREAD

**Issue by SakurasDuck** [mpflutter-plugins/universal_miniprogram_api#1]
![image](https://user-images.githubusercontent.com/40283698/147198858-8a46188b-0329-42c0-8302-242b2320f02a.png)
感谢!

**Comment by PonyCui** [comment]
这个组件的优化级较低，如果你有这方面的需求，不妨私聊作者，我们可以讨论一下是否可以提高优先级。

**Comment by SakurasDuck** [comment]
@PonyCui 我这里确实是有个这个需求,但是我认为地图组件还是有其他替代方案,优先级不会很高

**Comment by PonyCui** [comment]
我看看这周能不能把一些必要的组件补充一下，例如 Map / Ad 等。

**Comment by SakurasDuck** [comment]
@PonyCui 大佬辛苦,那这个我就先关了还是等大佬加上再关?

**Comment by PonyCui** [comment]
完善了再关

**Comment by PonyCui** [comment]
MapView 已经开发完毕了，测试完成后再跟随 mpflutter 0.11.0 版本发布。

**Comment by PonyCui** [comment]
mpflutter 0.11.0 + universal_miniprogram_api 0.3.0 已经发布，添加 WechatMiniProgramMapView 组件。
