### ISSUE TITLE
希望能支持API：wx.openEmbeddedMiniProgram(Object object)

### ISSUE THREAD

**Issue by Frully** [mpflutter-plugins/universal_miniprogram_api#6]
如题。
跳转接口有4个，其它3个都支持了，就差这一个了。

[https://developers.weixin.qq.com/miniprogram/dev/api/navigate/wx.openEmbeddedMiniProgram.html](https://developers.weixin.qq.com/miniprogram/dev/api/navigate/wx.openEmbeddedMiniProgram.html)

**Comment by PonyCui** [comment]
使用 0.1.2 版本即可
