### ISSUE TITLE
universal_miniprogram_api 中的  Array<dynamic> 如何传值

### ISSUE THREAD

**Issue by weifucheng1102** [mpflutter-plugins/universal_miniprogram_api#7]
<img width="417" alt="image" src="https://user-images.githubusercontent.com/39686870/216245871-d005ab20-f2b4-48ac-bb0f-1c9fd0c3eb6e.png">
如上图中 scanType 是Array<dynamic>? 类型  但是这么传值是报错的（The argument type 'List<String>' can't be assigned to the parameter type 'Array<dynamic>?'）

**Comment by PonyCui** [comment]
应该是个 BUG，我提一个 patch 版本。

**Comment by PonyCui** [comment]
使用 0.1.3 就可以了，感谢反馈。

**Comment by weifucheng1102** [comment]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/39686870/216255183-143cbd11-20db-4794-aa94-b2c0887a56d0.png">
使用0.1.3 universal_miniprogram_api 文件报错了

**Comment by PonyCui** [comment]
使用 0.1.4 吧
