### ISSUE TITLE
#7  使用0.1.3 后代码报错了

### ISSUE THREAD

**Issue by weifucheng1102** [mpflutter-plugins/universal_miniprogram_api#8]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/39686870/216255666-3a3e4f7a-02d3-4df2-a2a5-54acbae13233.png">

**Comment by PonyCui** [comment]
使用 0.1.4 吧

**Comment by weifucheng1102** [comment]
> 使用 0.1.4 吧

<img width="845" alt="image" src="https://user-images.githubusercontent.com/39686870/216263041-f80ba1c2-8b0d-417e-9b03-861796a772a3.png">
0.14 报这样的错误

**Comment by PonyCui** [comment]
0.1.5 吧，这个 tag 在本地验证过可以 build。
